version: '2'

services:

  application:
    container_name: scaffold_application
    build: .
    volumes: 
      - '.:/var/www'
    ports: 
      - 80:80
    env_file:
      - '.env.local'
  
  mysql:
    image: mariadb
    container_name: scaffold_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
