#!/usr/bin/php
<?php

/**
 *    Scaffold v0.1
 *    by the Codin' Co.
 *
 *    Command-line utilities are here. Not very interesting.
 */
 
include_once 'public/index.php';

if(version_compare(phpversion(), '5.3.8') < 0) {
    echo '
You are running PHP ' . phpversion() . ', which is just too old for Scaffold\'s mighty codebase.
Scaffold just won\'t work unless you upgrade. Sorry about that.

';
    exit;
}

$methods = array(
    'install' => function($arg) {
        if($arg) {
            echo $arg;
        }
    },
    
    'kitten' => function($arg) {
        //  Lovely kitten message
        echo 'Meow!'; sleep(1);
        
        //  And open a kitten
        `open http://cats.codin.co`;
    }
);

//  Check the argument(s)
if(!isset($argv[1])) {
    echo '
Welcome to the wonderful world of Scaffold! You\'re currently looking at version ' . SCAFFOLD_VERSION . ', which has the following commands available for you to use right now!
';
}

if(isset($methods[$argv[1]])) {
    $methods[$argv[1]]($argv[2]);
}

//  And new line, and we're done.
echo "\n";