#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/system/helpers.php';

use Illuminate\Database\Capsule\Manager;
use Scaffold\Console\Application;
use Scaffold\Foundation\Config;

$application = new Application(__DIR__, [
    'config'     => new Config(),
    'database'   => new Manager(),
]);

$application->run();